### ISSUE TITLE
Board file artifacts expire

### ISSUE THREAD

**Issue by kC0pter** [probe-rs/rusty-probe#14]
First of all, awesome project especially with having open source hardware. Big fan of it.

I love the fact that the pipeline builds the necessary board and assembly files for everything.
I noticed that the artifacts of the last pipeline run have expired.

It might be a good idea to either not let the latest artifact expire or "deploy" them to the release/tags section so they can be downloaded from there.

**Comment by berkus** [comment]
Indeed, wanted to check out the schematics only to find out that last successful build was over 6 months ago and all artifacts have since perished.

**Comment by korken89** [comment]
Thanks for the hint! Sorry for that happening. I'll see if I can revive the artifacts for the current board design and push a release.

**Comment by berkus** [comment]
@korken89 you need help with a little bit of more robust setup? I think the build artifact should be published as a release (attached to the generated release as a binary), then it will be preserved indefinitely.

**Comment by korken89** [comment]
I'd love some help :) I've never really tried the release workflow together with artifacts.

**Comment by berkus** [comment]
@korken89 check it out.
