### ISSUE TITLE
Voltage regulators

### ISSUE THREAD

**Issue by diggit** [probe-rs/rusty-probe#2]
Hi,
I was looking on schematic and voltage regulators caught my eye.

NCP133BMXADJTCG (U13, U14) is "End of Life" part https://www.onsemi.com/products/power-management/linear-regulators-ldo/ncp133. It's difficult to obtain from major distributors.

Why is U12 different from U13 and U14? It would make sense to use same part from BOM minimization point of view.

**Comment by korken89** [comment]
There are issues as there are requirements on the U13, U14 being adjustable.
I'm looking into replacing these though.

**Comment by korken89** [comment]
I have updated the design to they "sister" component to solve this issue.
