### ISSUE TITLE
UART pinout for vcp is incorrect

### ISSUE THREAD

**Issue by allexoll** [probe-rs/rusty-probe#5]
currently dir_vcp_rx/tx is on gpio25/24, and vcp_rx/tx on 18/19.

The issue is that 18/19 only have cts/rts capabilities on the rp2040, but not rx/tx. 

<img width="217" alt="image" src="https://user-images.githubusercontent.com/261441/193226708-ce28a990-d95c-40ab-b0c6-af799b11203a.png">

but gpio24/25 have uart1 rx/tx capabilities:
<img width="214" alt="Screenshot 2022-09-30 at 10 26 18" src="https://user-images.githubusercontent.com/261441/193226854-84922083-24fe-41d4-92e8-1a0b1dff9801.png">

i think just switching the two pinset would be enough for VCP to work. I currently have a start of impl for the vcp (using core1 since DMA has not yet landed in the hal), but it will need the correct pins for this to work.

**Comment by korken89** [comment]
Hi, thanks for reporting!

I have moved the pins to 20 and 21 in the latest commit:
![image](https://user-images.githubusercontent.com/913109/194775235-6d7a440d-02e9-4842-beae-4f35665db76a.png)
